import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { ParserRegistry } from './ParserRegistry';

const URI = 'file:///test.owl';
const ROOT = join(__dirname, '../../test-ontologies');

// ── Inline test ontologies ────────────────────────────────────────────────

// Functional Syntax — comment before Prefix declarations (RED: current startsWith check misses this)
const FUNC_WITH_COMMENT = [
  '# Generated by a tool',
  'Prefix(:=<http://example.org/#>)',
  'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)',
  'Ontology(<http://example.org/>',
  '  Declaration(Class(<http://example.org/#Animal>))',
  ')',
].join('\n');

const FUNC_BOM_COMMENT = '﻿' + FUNC_WITH_COMMENT;

// Functional Syntax — passes current startsWith check (regression)
const FUNC_SIMPLE = 'Ontology(<http://example.org/>)';

const FUNC_WITH_CLASSES = [
  'Prefix(:=<http://example.org/#>)',
  'Prefix(owl:=<http://www.w3.org/2002/07/owl#>)',
  'Ontology(<http://example.org/>',
  '  Declaration(Class(:Animal))',
  '  Declaration(Class(:Plant))',
  ')',
].join('\n');

// Manchester Syntax (RED: currently returns 'unknown' for owl-xml languageId)
const MANCH_SIMPLE = 'Ontology: <http://example.org/>\n';

const MANCH_WITH_PREFIX = [
  'Prefix: : <http://example.org/#>',
  '',
  'Ontology: <http://example.org/>',
  '',
  'Class: :Animal',
  '',
  'Class: :Plant',
].join('\n');

// Turtle (RED: currently returns 'unknown' for owl-xml languageId)
const TURTLE_AT_PREFIX = [
  '@prefix : <http://example.org/#> .',
  '@prefix owl: <http://www.w3.org/2002/07/owl#> .',
  '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .',
  '<http://example.org/> rdf:type owl:Ontology .',
  ':Animal rdf:type owl:Class .',
  ':Plant rdf:type owl:Class .',
].join('\n');

const TURTLE_AT_BASE = [
  '@base <http://example.org/> .',
  '@prefix owl: <http://www.w3.org/2002/07/owl#> .',
  '@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .',
  '<http://example.org/> rdf:type owl:Ontology .',
  '<http://example.org/#Animal> rdf:type owl:Class .',
].join('\n');

const TURTLE_PREFIX_KW = [
  'PREFIX : <http://example.org/#>',
  'PREFIX owl: <http://www.w3.org/2002/07/owl#>',
  'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>',
  '<http://example.org/> rdf:type owl:Ontology .',
  '<http://example.org/#Animal> rdf:type owl:Class .',
].join('\n');

const TURTLE_BASE_KW = [
  'BASE <http://example.org/>',
  'PREFIX owl: <http://www.w3.org/2002/07/owl#>',
  'PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>',
  '<http://example.org/> rdf:type owl:Ontology .',
].join('\n');

// ─────────────────────────────────────────────────────────────────────────────

describe('ParserRegistry — OWL format detection via owl-xml languageId', () => {

  // ── US1: OWL Functional Syntax ────────────────────────────────────────

  describe('US1: Functional Syntax .owl files', () => {
    it('regression: detects Ontology( at start as functional', () => {
      const model = ParserRegistry.parse(FUNC_SIMPLE, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('functional');
    });

    it('regression: detects Functional Syntax when Prefix( declarations precede Ontology(', () => {
      const model = ParserRegistry.parse(FUNC_WITH_CLASSES, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('functional');
      expect(model.classes.size).toBeGreaterThan(0);
    });

    it('RED: detects Functional Syntax when file starts with a # comment line', () => {
      const model = ParserRegistry.parse(FUNC_WITH_COMMENT, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('functional');
    });

    it('RED: detects Functional Syntax when file starts with UTF-8 BOM and a # comment', () => {
      const model = ParserRegistry.parse(FUNC_BOM_COMMENT, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('functional');
    });
  });

  // ── US2: Manchester Syntax ─────────────────────────────────────────────

  describe('US2: Manchester Syntax .owl files', () => {
    it('RED: detects Ontology: as manchester', () => {
      const model = ParserRegistry.parse(MANCH_SIMPLE, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('manchester');
    });

    it('RED: detects Manchester Syntax when preceded by Prefix: declarations and loads classes', () => {
      const model = ParserRegistry.parse(MANCH_WITH_PREFIX, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('manchester');
      expect(model.classes.size).toBeGreaterThan(0);
    });

    it('regression: does not misclassify Functional Syntax as manchester (paren vs colon)', () => {
      const model = ParserRegistry.parse(FUNC_SIMPLE, 'owl-xml', URI);
      expect(model.sourceFormat).not.toBe('manchester');
    });
  });

  // ── US2: Turtle ───────────────────────────────────────────────────────

  describe('US2: Turtle .owl files', () => {
    it('RED: detects @prefix directive as turtle and loads classes', () => {
      const model = ParserRegistry.parse(TURTLE_AT_PREFIX, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('turtle');
      expect(model.classes.size).toBeGreaterThan(0);
    });

    it('RED: detects @base directive as turtle', () => {
      const model = ParserRegistry.parse(TURTLE_AT_BASE, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('turtle');
    });

    it('RED: detects PREFIX keyword as turtle', () => {
      const model = ParserRegistry.parse(TURTLE_PREFIX_KW, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('turtle');
    });

    it('RED: detects BASE keyword as turtle', () => {
      const model = ParserRegistry.parse(TURTLE_BASE_KW, 'owl-xml', URI);
      expect(model.sourceFormat).toBe('turtle');
    });
  });

  // ── US3: Unknown / unrecognisable content ──────────────────────────────

  describe('US3: Unrecognisable .owl file produces clear error with URI', () => {
    it('throws for JSON content and includes the file URI in the error message', () => {
      const testUri = 'file:///my-ontology.owl';
      expect(() => ParserRegistry.parse('{ "key": "value" }', 'owl-xml', testUri))
        .toThrow(testUri);
    });

    it('throws for empty content', () => {
      expect(() => ParserRegistry.parse('', 'owl-xml', URI)).toThrow();
    });

    it('throws for plain text content', () => {
      expect(() => ParserRegistry.parse('Hello world', 'owl-xml', URI)).toThrow();
    });
  });

  // ── Regressions: existing .owl fixture files ───────────────────────────

  describe('Regression: existing .owl fixture files (skipped if test-ontologies/ absent)', () => {
    const pizzaPath = join(ROOT, 'pizza.owl');
    const animalsOwxPath = join(ROOT, 'animals.owx');

    (existsSync(pizzaPath) ? it : it.skip)(
      'pizza.owl (RDF/XML) still loads with sourceFormat rdf-xml',
      () => {
        const text = readFileSync(pizzaPath, 'utf8');
        const model = ParserRegistry.parse(text, 'owl-xml', `file://${pizzaPath}`);
        expect(model.sourceFormat).toBe('rdf-xml');
        expect(model.classes.size).toBeGreaterThan(0);
      },
    );

    (existsSync(animalsOwxPath) ? it : it.skip)(
      'animals.owx (OWL/XML) still loads with sourceFormat owl-xml',
      () => {
        const text = readFileSync(animalsOwxPath, 'utf8');
        const model = ParserRegistry.parse(text, 'owl-xml', `file://${animalsOwxPath}`);
        expect(model.sourceFormat).toBe('owl-xml');
        expect(model.classes.size).toBeGreaterThan(0);
      },
    );
  });
});
