import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

/**
 * Self-contained replacement for `npm link`-based CLI installation (see cliInstaller.ts for the
 * "why"). Everything here writes to a fixed, version-independent location under
 * `~/.ontograph-editor/` (the existing convention from sessionFile.ts) so the CLI's presence
 * never depends on which npm/Node the extension host process happens to resolve.
 *
 * Deliberately `.ontograph-editor`, not the shorter `.ontograph`: this repo bundles OntoGraph-lite
 * too, whose own CLI (`@ysgao/ontograph-cli`) uses `~/.ontograph-lite/` — a bare `.ontograph` would
 * read as a typo of (or future collision with) that sibling convention.
 *
 * Pure string-building functions (no fs/child_process) are kept separate from the I/O-performing
 * `ensure*`/`write*` functions below them, so the former can be unit-tested without mocking fs.
 */

export const ONTOGRAPH_DIR = path.join(os.homedir(), '.ontograph-editor');
export const BIN_DIR = path.join(ONTOGRAPH_DIR, 'bin');
export const UNIX_SHIM_PATH = path.join(BIN_DIR, 'authoring-cli');
export const WINDOWS_SHIM_PATH = path.join(BIN_DIR, 'authoring-cli.cmd');
export const ENV_SH_PATH = path.join(ONTOGRAPH_DIR, 'env.sh');
export const ENV_FISH_PATH = path.join(ONTOGRAPH_DIR, 'env.fish');
export const WINDOWS_PATH_SCRIPT_PATH = path.join(ONTOGRAPH_DIR, 'set-path.ps1');

const WINDOWS_PATH_TIMEOUT_MS = 15000;

// Shell-variable form (not a resolved fs path) so env.sh/env.fish stay human-readable/portable.
const BIN_DIR_SHELL_VAR = '$HOME/.ontograph-editor/bin';

export const MARKER_BEGIN = '# >>> ontograph authoring-cli >>>';
export const MARKER_END = '# <<< ontograph authoring-cli <<<';

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Removes every existing marker-guarded block (however many, however malformed-but-paired) and
 * appends exactly one fresh copy of `blockBody`. This "strip all, append one" shape — rather than
 * "append only if absent" — is what makes it race-safe under two VS Code windows activating
 * concurrently: the appended block is always byte-identical for a given blockBody, so whichever
 * write lands last still leaves the file in the same canonical single-block state. Always
 * separates the block from prior content with a blank line, so a file whose last line has no
 * trailing newline never gets corrupted by a naive concatenation.
 */
export function upsertMarkerBlock(content: string, blockBody: string): string {
  const blockRegex = new RegExp(
    `\\n?${escapeRegExp(MARKER_BEGIN)}[\\s\\S]*?${escapeRegExp(MARKER_END)}\\n?`,
    'g'
  );
  const stripped = content.replace(blockRegex, '');
  const trimmed = stripped.replace(/\s+$/, '');
  const block = `${MARKER_BEGIN}\n${blockBody}\n${MARKER_END}\n`;
  return trimmed.length === 0 ? block : `${trimmed}\n\n${block}`;
}

/** POSIX sh, sourced by rc files below — idempotent even if sourced more than once per shell. */
export function buildEnvShContent(binDir: string): string {
  return [
    '#!/bin/sh',
    '# OntoGraph Editor: puts authoring-cli on PATH. Auto-generated — do not edit by hand.',
    'case ":${PATH}:" in',
    `  *":${binDir}:"*) ;;`,
    `  *) export PATH="${binDir}:$PATH" ;;`,
    'esac',
    '',
  ].join('\n');
}

export function buildEnvFishContent(binDir: string): string {
  return [
    '# OntoGraph Editor: puts authoring-cli on PATH. Auto-generated — do not edit by hand.',
    `if not contains ${binDir} $PATH`,
    `    set -gx PATH ${binDir} $PATH`,
    'end',
    '',
  ].join('\n');
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`;
}

/**
 * Prefers `node` on PATH (respects nvm/volta version pins); falls back to the IDE's own bundled
 * Electron runtime via ELECTRON_RUN_AS_NODE so the CLI still works with zero Node installed
 * system-wide — the target users are clinical terminologists, not developers.
 */
export function buildUnixShimContent(entryJsPath: string, execPath: string): string {
  return [
    '#!/bin/sh',
    '# Auto-generated by OntoGraph Editor. Overwritten on every extension update — do not edit.',
    `CLI_JS=${shellSingleQuote(entryJsPath)}`,
    'if command -v node >/dev/null 2>&1; then',
    '  exec node "$CLI_JS" "$@"',
    'else',
    '  export ELECTRON_RUN_AS_NODE=1',
    `  exec ${shellSingleQuote(execPath)} "$CLI_JS" "$@"`,
    'fi',
    '',
  ].join('\n');
}

export function buildWindowsShimContent(entryJsPath: string, execPath: string): string {
  return [
    '@echo off',
    'setlocal',
    `set "CLI_JS=${entryJsPath}"`,
    'where node >nul 2>nul',
    'if %ERRORLEVEL%==0 (',
    '  node "%CLI_JS%" %*',
    ') else (',
    '  set "ELECTRON_RUN_AS_NODE=1"',
    `  "${execPath}" "%CLI_JS%" %*`,
    ')',
    'endlocal',
    '',
  ].join('\r\n');
}

/**
 * No path is interpolated from Node into this script — it resolves $env:USERPROFILE and does its
 * own idempotent check-and-append entirely inside PowerShell. Deliberately not `setx`, which
 * silently truncates PATH values over ~1024 chars.
 */
export function buildWindowsPathScript(): string {
  return [
    '$binDir = Join-Path $env:USERPROFILE ".ontograph-editor\\bin"',
    "$current = [Environment]::GetEnvironmentVariable('Path', 'User')",
    'if ($null -eq $current) { $current = "" }',
    '$entries = $current -split ";" | Where-Object { $_ -ne "" }',
    '$alreadyPresent = $entries | Where-Object { $_.TrimEnd("\\") -ieq $binDir.TrimEnd("\\") }',
    'if (-not $alreadyPresent) {',
    '  $newValue = if ($current -eq "") { $binDir } else { "$binDir;$current" }',
    "  [Environment]::SetEnvironmentVariable('Path', $newValue, 'User')",
    '}',
    '',
  ].join('\r\n');
}

/** Case-insensitive, trailing-slash-tolerant membership check for a PATH-style delimited string. */
export function isDirOnPathValue(pathValue: string, dir: string, delimiter: string = path.delimiter): boolean {
  const normalize = (value: string): string => value.trim().replace(/[\\/]+$/, '').toLowerCase();
  const target = normalize(dir);
  if (!pathValue || !target) {
    return false;
  }
  return pathValue.split(delimiter).some((entry) => normalize(entry) === target);
}

/**
 * Deliberately ignores $ZDOTDIR: it comes from the extension host's own environment, which is
 * exactly the kind of value this whole rewrite exists to stop trusting (some tools point it
 * somewhere other than the user's real home directory for their own purposes — writing there
 * would be a bug of the same shape as `npm link` resolving the wrong Node). Users with a custom
 * ZDOTDIR zsh setup won't get zsh coverage from this mechanism, but still get bash/profile
 * coverage, or can fall back to the manual "OntoGraph: Set Up authoring-cli Command".
 */
function unixRcFiles(): string[] {
  const home = os.homedir();
  return [
    path.join(home, '.zshrc'),
    path.join(home, '.bash_profile'),
    path.join(home, '.bashrc'),
    path.join(home, '.profile'),
  ];
}

function fishConfigDir(): string {
  return path.join(os.homedir(), '.config', 'fish');
}

export interface ShimWriteResult {
  shimPath: string;
}

/** Writes the platform-appropriate shim, chmod'd 0o755 on Unix. Rewritten on every version bump. */
export function writeShimFiles(entryJsPath: string, execPath: string): ShimWriteResult {
  fs.mkdirSync(BIN_DIR, { recursive: true });
  if (process.platform === 'win32') {
    fs.writeFileSync(WINDOWS_SHIM_PATH, buildWindowsShimContent(entryJsPath, execPath));
    return { shimPath: WINDOWS_SHIM_PATH };
  }
  fs.writeFileSync(UNIX_SHIM_PATH, buildUnixShimContent(entryJsPath, execPath));
  fs.chmodSync(UNIX_SHIM_PATH, 0o755);
  return { shimPath: UNIX_SHIM_PATH };
}

export interface PathConfigResult {
  updatedFiles: string[];
}

/** Idempotent — safe to call on every activation, not just on version changes. */
export function ensureUnixPathConfigured(): PathConfigResult {
  fs.mkdirSync(ONTOGRAPH_DIR, { recursive: true });
  fs.writeFileSync(ENV_SH_PATH, buildEnvShContent(BIN_DIR_SHELL_VAR));
  fs.writeFileSync(ENV_FISH_PATH, buildEnvFishContent(BIN_DIR_SHELL_VAR));

  const updatedFiles: string[] = [];
  const sourceLine = `. ${shellSingleQuote(ENV_SH_PATH)}`;
  for (const rcFile of unixRcFiles()) {
    const existing = fs.existsSync(rcFile) ? fs.readFileSync(rcFile, 'utf8') : '';
    const updated = upsertMarkerBlock(existing, sourceLine);
    if (updated !== existing) {
      fs.writeFileSync(rcFile, updated);
      updatedFiles.push(rcFile);
    }
  }

  const fishDir = fishConfigDir();
  if (fs.existsSync(fishDir)) {
    const fishConfFile = path.join(fishDir, 'conf.d', 'ontograph-authoring-cli.fish');
    fs.mkdirSync(path.dirname(fishConfFile), { recursive: true });
    fs.writeFileSync(fishConfFile, `source ${shellSingleQuote(ENV_FISH_PATH)}\n`);
    updatedFiles.push(fishConfFile);
  }

  return { updatedFiles };
}

export interface WindowsPathConfigResult {
  ran: boolean;
}

/**
 * Windows GUI apps inherit the real, registry-persisted user PATH at launch (unlike macOS/Linux
 * GUI apps, which typically get a bare launchd/systemd PATH) — so `process.env.PATH` here is a
 * reliable signal for "already configured," letting us skip shelling out to PowerShell on every
 * activation once it's done once.
 */
export async function ensureWindowsPathConfigured(): Promise<WindowsPathConfigResult> {
  if (isDirOnPathValue(process.env.PATH || '', BIN_DIR)) {
    return { ran: false };
  }
  fs.mkdirSync(ONTOGRAPH_DIR, { recursive: true });
  fs.writeFileSync(WINDOWS_PATH_SCRIPT_PATH, buildWindowsPathScript());
  await execAsync(
    `powershell -NoProfile -ExecutionPolicy Bypass -File "${WINDOWS_PATH_SCRIPT_PATH}"`,
    { timeout: WINDOWS_PATH_TIMEOUT_MS }
  );
  return { ran: true };
}
